# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_metacoop_cpp <- function(Xmat_list, Y_list, nvars, nlambda, NOBS_PER_STUDY_, weights_list, LAMBDA_) {
    .Call('_metacoop_fit_metacoop_cpp', PACKAGE = 'metacoop', Xmat_list, Y_list, nvars, nlambda, NOBS_PER_STUDY_, weights_list, LAMBDA_)
}

